/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FundraiserService } from "../fundraiser.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FundraiserCreateInput } from "./FundraiserCreateInput";
import { Fundraiser } from "./Fundraiser";
import { FundraiserFindManyArgs } from "./FundraiserFindManyArgs";
import { FundraiserWhereUniqueInput } from "./FundraiserWhereUniqueInput";
import { FundraiserUpdateInput } from "./FundraiserUpdateInput";
import { DonationFindManyArgs } from "../../donation/base/DonationFindManyArgs";
import { Donation } from "../../donation/base/Donation";
import { DonationWhereUniqueInput } from "../../donation/base/DonationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FundraiserControllerBase {
  constructor(
    protected readonly service: FundraiserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Fundraiser })
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFundraiser(
    @common.Body() data: FundraiserCreateInput
  ): Promise<Fundraiser> {
    return await this.service.createFundraiser({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        goalAmount: true,
        currentAmount: true,
        organization: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Fundraiser] })
  @ApiNestedQuery(FundraiserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async fundraisers(@common.Req() request: Request): Promise<Fundraiser[]> {
    const args = plainToClass(FundraiserFindManyArgs, request.query);
    return this.service.fundraisers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        goalAmount: true,
        currentAmount: true,
        organization: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async fundraiser(
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Fundraiser | null> {
    const result = await this.service.fundraiser({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        goalAmount: true,
        currentAmount: true,
        organization: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFundraiser(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() data: FundraiserUpdateInput
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.updateFundraiser({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          goalAmount: true,
          currentAmount: true,
          organization: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Fundraiser })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFundraiser(
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.deleteFundraiser({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          goalAmount: true,
          currentAmount: true,
          organization: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/donations")
  @ApiNestedQuery(DonationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async findDonations(
    @common.Req() request: Request,
    @common.Param() params: FundraiserWhereUniqueInput
  ): Promise<Donation[]> {
    const query = plainToClass(DonationFindManyArgs, request.query);
    const results = await this.service.findDonations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        date: true,

        volunteer: {
          select: {
            id: true,
          },
        },

        fundraiser: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "update",
    possession: "any",
  })
  async connectDonations(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        connect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "update",
    possession: "any",
  })
  async updateDonations(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        set: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "update",
    possession: "any",
  })
  async disconnectDonations(
    @common.Param() params: FundraiserWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        disconnect: body,
      },
    };
    await this.service.updateFundraiser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
