/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Fundraiser } from "./Fundraiser";
import { FundraiserCountArgs } from "./FundraiserCountArgs";
import { FundraiserFindManyArgs } from "./FundraiserFindManyArgs";
import { FundraiserFindUniqueArgs } from "./FundraiserFindUniqueArgs";
import { CreateFundraiserArgs } from "./CreateFundraiserArgs";
import { UpdateFundraiserArgs } from "./UpdateFundraiserArgs";
import { DeleteFundraiserArgs } from "./DeleteFundraiserArgs";
import { DonationFindManyArgs } from "../../donation/base/DonationFindManyArgs";
import { Donation } from "../../donation/base/Donation";
import { FundraiserService } from "../fundraiser.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Fundraiser)
export class FundraiserResolverBase {
  constructor(
    protected readonly service: FundraiserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "read",
    possession: "any",
  })
  async _fundraisersMeta(
    @graphql.Args() args: FundraiserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fundraiser])
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "read",
    possession: "any",
  })
  async fundraisers(
    @graphql.Args() args: FundraiserFindManyArgs
  ): Promise<Fundraiser[]> {
    return this.service.fundraisers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fundraiser, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "read",
    possession: "own",
  })
  async fundraiser(
    @graphql.Args() args: FundraiserFindUniqueArgs
  ): Promise<Fundraiser | null> {
    const result = await this.service.fundraiser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Fundraiser)
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "create",
    possession: "any",
  })
  async createFundraiser(
    @graphql.Args() args: CreateFundraiserArgs
  ): Promise<Fundraiser> {
    return await this.service.createFundraiser({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Fundraiser)
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "update",
    possession: "any",
  })
  async updateFundraiser(
    @graphql.Args() args: UpdateFundraiserArgs
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.updateFundraiser({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Fundraiser)
  @nestAccessControl.UseRoles({
    resource: "Fundraiser",
    action: "delete",
    possession: "any",
  })
  async deleteFundraiser(
    @graphql.Args() args: DeleteFundraiserArgs
  ): Promise<Fundraiser | null> {
    try {
      return await this.service.deleteFundraiser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Donation], { name: "donations" })
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async findDonations(
    @graphql.Parent() parent: Fundraiser,
    @graphql.Args() args: DonationFindManyArgs
  ): Promise<Donation[]> {
    const results = await this.service.findDonations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
