/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Fundraiser as PrismaFundraiser,
  Donation as PrismaDonation,
} from "@prisma/client";

export class FundraiserServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FundraiserCountArgs, "select">
  ): Promise<number> {
    return this.prisma.fundraiser.count(args);
  }

  async fundraisers(
    args: Prisma.FundraiserFindManyArgs
  ): Promise<PrismaFundraiser[]> {
    return this.prisma.fundraiser.findMany(args);
  }
  async fundraiser(
    args: Prisma.FundraiserFindUniqueArgs
  ): Promise<PrismaFundraiser | null> {
    return this.prisma.fundraiser.findUnique(args);
  }
  async createFundraiser(
    args: Prisma.FundraiserCreateArgs
  ): Promise<PrismaFundraiser> {
    return this.prisma.fundraiser.create(args);
  }
  async updateFundraiser(
    args: Prisma.FundraiserUpdateArgs
  ): Promise<PrismaFundraiser> {
    return this.prisma.fundraiser.update(args);
  }
  async deleteFundraiser(
    args: Prisma.FundraiserDeleteArgs
  ): Promise<PrismaFundraiser> {
    return this.prisma.fundraiser.delete(args);
  }

  async findDonations(
    parentId: string,
    args: Prisma.DonationFindManyArgs
  ): Promise<PrismaDonation[]> {
    return this.prisma.fundraiser
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .donations(args);
  }
}
