/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ForumPost } from "./ForumPost";
import { ForumPostCountArgs } from "./ForumPostCountArgs";
import { ForumPostFindManyArgs } from "./ForumPostFindManyArgs";
import { ForumPostFindUniqueArgs } from "./ForumPostFindUniqueArgs";
import { CreateForumPostArgs } from "./CreateForumPostArgs";
import { UpdateForumPostArgs } from "./UpdateForumPostArgs";
import { DeleteForumPostArgs } from "./DeleteForumPostArgs";
import { ForumPostService } from "../forumPost.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ForumPost)
export class ForumPostResolverBase {
  constructor(
    protected readonly service: ForumPostService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "read",
    possession: "any",
  })
  async _forumPostsMeta(
    @graphql.Args() args: ForumPostCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ForumPost])
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "read",
    possession: "any",
  })
  async forumPosts(
    @graphql.Args() args: ForumPostFindManyArgs
  ): Promise<ForumPost[]> {
    return this.service.forumPosts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ForumPost, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "read",
    possession: "own",
  })
  async forumPost(
    @graphql.Args() args: ForumPostFindUniqueArgs
  ): Promise<ForumPost | null> {
    const result = await this.service.forumPost(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ForumPost)
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "create",
    possession: "any",
  })
  async createForumPost(
    @graphql.Args() args: CreateForumPostArgs
  ): Promise<ForumPost> {
    return await this.service.createForumPost({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ForumPost)
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "update",
    possession: "any",
  })
  async updateForumPost(
    @graphql.Args() args: UpdateForumPostArgs
  ): Promise<ForumPost | null> {
    try {
      return await this.service.updateForumPost({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ForumPost)
  @nestAccessControl.UseRoles({
    resource: "ForumPost",
    action: "delete",
    possession: "any",
  })
  async deleteForumPost(
    @graphql.Args() args: DeleteForumPostArgs
  ): Promise<ForumPost | null> {
    try {
      return await this.service.deleteForumPost(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
