/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, ForumPost as PrismaForumPost } from "@prisma/client";

export class ForumPostServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ForumPostCountArgs, "select">
  ): Promise<number> {
    return this.prisma.forumPost.count(args);
  }

  async forumPosts(
    args: Prisma.ForumPostFindManyArgs
  ): Promise<PrismaForumPost[]> {
    return this.prisma.forumPost.findMany(args);
  }
  async forumPost(
    args: Prisma.ForumPostFindUniqueArgs
  ): Promise<PrismaForumPost | null> {
    return this.prisma.forumPost.findUnique(args);
  }
  async createForumPost(
    args: Prisma.ForumPostCreateArgs
  ): Promise<PrismaForumPost> {
    return this.prisma.forumPost.create(args);
  }
  async updateForumPost(
    args: Prisma.ForumPostUpdateArgs
  ): Promise<PrismaForumPost> {
    return this.prisma.forumPost.update(args);
  }
  async deleteForumPost(
    args: Prisma.ForumPostDeleteArgs
  ): Promise<PrismaForumPost> {
    return this.prisma.forumPost.delete(args);
  }
}
