/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { VolunteerWhereUniqueInput } from "../../volunteer/base/VolunteerWhereUniqueInput";
import { CommentCreateNestedManyWithoutStoriesInput } from "./CommentCreateNestedManyWithoutStoriesInput";

@InputType()
class StoryCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  content?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  image?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VolunteerWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VolunteerWhereUniqueInput)
  @IsOptional()
  @Field(() => VolunteerWhereUniqueInput, {
    nullable: true,
  })
  volunteer?: VolunteerWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutStoriesInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutStoriesInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutStoriesInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutStoriesInput;
}

export { StoryCreateInput as StoryCreateInput };
