/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StoryCreateNestedManyWithoutVolunteersInput } from "./StoryCreateNestedManyWithoutVolunteersInput";
import { Type } from "class-transformer";
import { DonationCreateNestedManyWithoutVolunteersInput } from "./DonationCreateNestedManyWithoutVolunteersInput";
import { CommentCreateNestedManyWithoutVolunteersInput } from "./CommentCreateNestedManyWithoutVolunteersInput";

@InputType()
class VolunteerCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => StoryCreateNestedManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => StoryCreateNestedManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => StoryCreateNestedManyWithoutVolunteersInput, {
    nullable: true,
  })
  stories?: StoryCreateNestedManyWithoutVolunteersInput;

  @ApiProperty({
    required: false,
    type: () => DonationCreateNestedManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => DonationCreateNestedManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => DonationCreateNestedManyWithoutVolunteersInput, {
    nullable: true,
  })
  donations?: DonationCreateNestedManyWithoutVolunteersInput;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutVolunteersInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutVolunteersInput;
}

export { VolunteerCreateInput as VolunteerCreateInput };
