/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { StoryUpdateManyWithoutVolunteersInput } from "./StoryUpdateManyWithoutVolunteersInput";
import { Type } from "class-transformer";
import { DonationUpdateManyWithoutVolunteersInput } from "./DonationUpdateManyWithoutVolunteersInput";
import { CommentUpdateManyWithoutVolunteersInput } from "./CommentUpdateManyWithoutVolunteersInput";

@InputType()
class VolunteerUpdateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => StoryUpdateManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => StoryUpdateManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => StoryUpdateManyWithoutVolunteersInput, {
    nullable: true,
  })
  stories?: StoryUpdateManyWithoutVolunteersInput;

  @ApiProperty({
    required: false,
    type: () => DonationUpdateManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => DonationUpdateManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => DonationUpdateManyWithoutVolunteersInput, {
    nullable: true,
  })
  donations?: DonationUpdateManyWithoutVolunteersInput;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutVolunteersInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutVolunteersInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutVolunteersInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutVolunteersInput;
}

export { VolunteerUpdateInput as VolunteerUpdateInput };
