/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { VolunteerService } from "../volunteer.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { VolunteerCreateInput } from "./VolunteerCreateInput";
import { Volunteer } from "./Volunteer";
import { VolunteerFindManyArgs } from "./VolunteerFindManyArgs";
import { VolunteerWhereUniqueInput } from "./VolunteerWhereUniqueInput";
import { VolunteerUpdateInput } from "./VolunteerUpdateInput";
import { StoryFindManyArgs } from "../../story/base/StoryFindManyArgs";
import { Story } from "../../story/base/Story";
import { StoryWhereUniqueInput } from "../../story/base/StoryWhereUniqueInput";
import { DonationFindManyArgs } from "../../donation/base/DonationFindManyArgs";
import { Donation } from "../../donation/base/Donation";
import { DonationWhereUniqueInput } from "../../donation/base/DonationWhereUniqueInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class VolunteerControllerBase {
  constructor(
    protected readonly service: VolunteerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Volunteer })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createVolunteer(
    @common.Body() data: VolunteerCreateInput
  ): Promise<Volunteer> {
    return await this.service.createVolunteer({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        profilePicture: true,
        bio: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Volunteer] })
  @ApiNestedQuery(VolunteerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async volunteers(@common.Req() request: Request): Promise<Volunteer[]> {
    const args = plainToClass(VolunteerFindManyArgs, request.query);
    return this.service.volunteers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        profilePicture: true,
        bio: true,
        name: true,
        email: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async volunteer(
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Volunteer | null> {
    const result = await this.service.volunteer({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        profilePicture: true,
        bio: true,
        name: true,
        email: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateVolunteer(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() data: VolunteerUpdateInput
  ): Promise<Volunteer | null> {
    try {
      return await this.service.updateVolunteer({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          profilePicture: true,
          bio: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Volunteer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteVolunteer(
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Volunteer | null> {
    try {
      return await this.service.deleteVolunteer({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          profilePicture: true,
          bio: true,
          name: true,
          email: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/stories")
  @ApiNestedQuery(StoryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Story",
    action: "read",
    possession: "any",
  })
  async findStories(
    @common.Req() request: Request,
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Story[]> {
    const query = plainToClass(StoryFindManyArgs, request.query);
    const results = await this.service.findStories(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        content: true,
        image: true,

        category: {
          select: {
            id: true,
          },
        },

        volunteer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stories")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async connectStories(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        connect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stories")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async updateStories(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        set: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stories")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async disconnectStories(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: StoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stories: {
        disconnect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/donations")
  @ApiNestedQuery(DonationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Donation",
    action: "read",
    possession: "any",
  })
  async findDonations(
    @common.Req() request: Request,
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Donation[]> {
    const query = plainToClass(DonationFindManyArgs, request.query);
    const results = await this.service.findDonations(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        date: true,

        volunteer: {
          select: {
            id: true,
          },
        },

        fundraiser: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async connectDonations(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        connect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async updateDonations(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        set: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/donations")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async disconnectDonations(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        disconnect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Comment",
    action: "read",
    possession: "any",
  })
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: VolunteerWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,

        story: {
          select: {
            id: true,
          },
        },

        volunteer: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async connectComments(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async updateComments(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  @nestAccessControl.UseRoles({
    resource: "Volunteer",
    action: "update",
    possession: "any",
  })
  async disconnectComments(
    @common.Param() params: VolunteerWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateVolunteer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
