/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { VolunteerOpportunityService } from "../volunteerOpportunity.service";
import { VolunteerOpportunityCreateInput } from "./VolunteerOpportunityCreateInput";
import { VolunteerOpportunity } from "./VolunteerOpportunity";
import { VolunteerOpportunityFindManyArgs } from "./VolunteerOpportunityFindManyArgs";
import { VolunteerOpportunityWhereUniqueInput } from "./VolunteerOpportunityWhereUniqueInput";
import { VolunteerOpportunityUpdateInput } from "./VolunteerOpportunityUpdateInput";

export class VolunteerOpportunityControllerBase {
  constructor(protected readonly service: VolunteerOpportunityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: VolunteerOpportunity })
  async createVolunteerOpportunity(
    @common.Body() data: VolunteerOpportunityCreateInput
  ): Promise<VolunteerOpportunity> {
    return await this.service.createVolunteerOpportunity({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        location: true,
        eventDate: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [VolunteerOpportunity] })
  @ApiNestedQuery(VolunteerOpportunityFindManyArgs)
  async volunteerOpportunities(
    @common.Req() request: Request
  ): Promise<VolunteerOpportunity[]> {
    const args = plainToClass(VolunteerOpportunityFindManyArgs, request.query);
    return this.service.volunteerOpportunities({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        location: true,
        eventDate: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: VolunteerOpportunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async volunteerOpportunity(
    @common.Param() params: VolunteerOpportunityWhereUniqueInput
  ): Promise<VolunteerOpportunity | null> {
    const result = await this.service.volunteerOpportunity({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        location: true,
        eventDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: VolunteerOpportunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateVolunteerOpportunity(
    @common.Param() params: VolunteerOpportunityWhereUniqueInput,
    @common.Body() data: VolunteerOpportunityUpdateInput
  ): Promise<VolunteerOpportunity | null> {
    try {
      return await this.service.updateVolunteerOpportunity({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          location: true,
          eventDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: VolunteerOpportunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteVolunteerOpportunity(
    @common.Param() params: VolunteerOpportunityWhereUniqueInput
  ): Promise<VolunteerOpportunity | null> {
    try {
      return await this.service.deleteVolunteerOpportunity({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          location: true,
          eventDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
