/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { VolunteerOpportunity } from "./VolunteerOpportunity";
import { VolunteerOpportunityCountArgs } from "./VolunteerOpportunityCountArgs";
import { VolunteerOpportunityFindManyArgs } from "./VolunteerOpportunityFindManyArgs";
import { VolunteerOpportunityFindUniqueArgs } from "./VolunteerOpportunityFindUniqueArgs";
import { CreateVolunteerOpportunityArgs } from "./CreateVolunteerOpportunityArgs";
import { UpdateVolunteerOpportunityArgs } from "./UpdateVolunteerOpportunityArgs";
import { DeleteVolunteerOpportunityArgs } from "./DeleteVolunteerOpportunityArgs";
import { VolunteerOpportunityService } from "../volunteerOpportunity.service";
@graphql.Resolver(() => VolunteerOpportunity)
export class VolunteerOpportunityResolverBase {
  constructor(protected readonly service: VolunteerOpportunityService) {}

  async _volunteerOpportunitiesMeta(
    @graphql.Args() args: VolunteerOpportunityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [VolunteerOpportunity])
  async volunteerOpportunities(
    @graphql.Args() args: VolunteerOpportunityFindManyArgs
  ): Promise<VolunteerOpportunity[]> {
    return this.service.volunteerOpportunities(args);
  }

  @graphql.Query(() => VolunteerOpportunity, { nullable: true })
  async volunteerOpportunity(
    @graphql.Args() args: VolunteerOpportunityFindUniqueArgs
  ): Promise<VolunteerOpportunity | null> {
    const result = await this.service.volunteerOpportunity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => VolunteerOpportunity)
  async createVolunteerOpportunity(
    @graphql.Args() args: CreateVolunteerOpportunityArgs
  ): Promise<VolunteerOpportunity> {
    return await this.service.createVolunteerOpportunity({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => VolunteerOpportunity)
  async updateVolunteerOpportunity(
    @graphql.Args() args: UpdateVolunteerOpportunityArgs
  ): Promise<VolunteerOpportunity | null> {
    try {
      return await this.service.updateVolunteerOpportunity({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VolunteerOpportunity)
  async deleteVolunteerOpportunity(
    @graphql.Args() args: DeleteVolunteerOpportunityArgs
  ): Promise<VolunteerOpportunity | null> {
    try {
      return await this.service.deleteVolunteerOpportunity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
