/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  VolunteerOpportunity as PrismaVolunteerOpportunity,
} from "@prisma/client";

export class VolunteerOpportunityServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.VolunteerOpportunityCountArgs, "select">
  ): Promise<number> {
    return this.prisma.volunteerOpportunity.count(args);
  }

  async volunteerOpportunities(
    args: Prisma.VolunteerOpportunityFindManyArgs
  ): Promise<PrismaVolunteerOpportunity[]> {
    return this.prisma.volunteerOpportunity.findMany(args);
  }
  async volunteerOpportunity(
    args: Prisma.VolunteerOpportunityFindUniqueArgs
  ): Promise<PrismaVolunteerOpportunity | null> {
    return this.prisma.volunteerOpportunity.findUnique(args);
  }
  async createVolunteerOpportunity(
    args: Prisma.VolunteerOpportunityCreateArgs
  ): Promise<PrismaVolunteerOpportunity> {
    return this.prisma.volunteerOpportunity.create(args);
  }
  async updateVolunteerOpportunity(
    args: Prisma.VolunteerOpportunityUpdateArgs
  ): Promise<PrismaVolunteerOpportunity> {
    return this.prisma.volunteerOpportunity.update(args);
  }
  async deleteVolunteerOpportunity(
    args: Prisma.VolunteerOpportunityDeleteArgs
  ): Promise<PrismaVolunteerOpportunity> {
    return this.prisma.volunteerOpportunity.delete(args);
  }
}
